[server]
hostname = subscription.rhsm.redhat.com
prefix = /subscription
port = 443
insecure = 0
proxy_hostname =
proxy_scheme =
proxy_port =
proxy_user =
proxy_password =
no_proxy =

[rhsm]
ca_cert_dir = /etc/rhsm/ca/
repo_ca_cert = %(ca_cert_dir)sredhat-uep.pem
