[http.timeout]
connect = 30
request = 30
idle = 120

[http.proxy]
uri = ""
username = ""
password = ""
no-proxy = []

[api.heartbeat]
uri = "https://cert.console.redhat.com/api/rhel-telemetry/v1/receive"
tls-verify = true
ca-path = "system"
